language: python
python:
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - visdom -logging_level=CRITICAL &
  - pycodestyle --statistics tests --show-source --max-line-length=120
  - pycodestyle --statistics torchtrainer --show-source --max-line-length=120
  - pytest --cov-report term --cov=torchtrainer tests/
after_success:
  - codecov
