ROOT_PATH = ''

# general inputs
NODE2VEC_EXECUTABLE_PATH = ''
NODE2VEC_SAVE_DIR = ''
NODE2VEC_GRAPH_INPUT = ''
CHECKPOINT_SAVE_PATH = ''
WORD_EMBEDDING_PATH = ''
DICTIONARY_PATH = ''
COMMENT_ID_TO_AUTHOR_DICT_PATH = ''
TRAIN_SET_ALL_PATH = ''
CORPUS_COMMENT_ID_TO_INDEX = ''
TOKENIZED_COMMENTS_PATH = ''

# point
TRAINING_DATA_PATH = ''
POSITIVE_NEGATIVE_PATH = ''
VAL_DATA_PATH = ''

LINE_OFFSET_DICT_PATH = ''
LINE_OFFSET_DICT_PATH_VAL = ''

# l2r
POSITIVE_NEGATIVE_PATH_L2R = ''
VAL_DATA_PATH_L2R = ''
LINE_TRAIN_OFFSET_DICT_PATH_L2R = ''
LINE_VAL_OFFSET_DICT_PATH_L2R = ''

#
SHUFFLE = True
CHECKPOINT_EVERY = 5000
DEV_EVERY = 100
PRINT_PROGRESS_EVERY = 100


# CNN Input Sizes
MAX_COMMENTS_USER_SECTION = 42
MAX_COMMENTS_SECTION = 40
MAX_LENGHT_COMMENT = 94
MAX_LENGTH_USER_REPRESENATION = MAX_COMMENTS_USER_SECTION * MAX_LENGHT_COMMENT
MAX_LENGTH_COMMENT_SECTION = MAX_COMMENTS_SECTION * MAX_LENGHT_COMMENT

